db:
  url: postgresql://localhost:5432/weather
  user: postgres
  password: admin


spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: false
  r2dbc:
    url: 'r2dbc:${db.url}'
    username: ${db.user}
    password: ${db.password}
    pool:
      enabled: true
      initial-size: '10'
      max-idle-time: 1m
      max-size: '30'
  data:
    r2dbc:
      repositories:
        enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8060